### ISSUE TITLE
[while] shows error

### ISSUE THREAD

**Issue by juqkai** [andreaval/FlowgorithmJS#1]
[Guess a number.fprg](https://github.com/deep-dive-coding-java-cohort-6/guess-number/blob/master/docs/Guess%20a%20number.fprg)

![image](https://user-images.githubusercontent.com/436109/52997388-643e8d00-345b-11e9-9b0b-7e7926325dce.png)

[while] shows error

**Comment by andreaval** [comment]
I solved this problem in version 0.14
Thanks for the error report
